### ISSUE TITLE
Error: Type with name "SanityDocument" does not exists

### ISSUE THREAD

**Issue by michahell** [sanity-io/gridsome-source-sanity#11]
I'm building and experimenting on top of the `gridsome-sanity-blog-starter`.
I made some changes to my sanity schema and those changes appear valid: 
Sanity studio compiles, I can go to `localhost:3333/desk/<newDocumentType>` and see and interact with my newly created types.

However, gridsome won't compile: I'm getting this error and I have no clue where to start looking:

`sanity-gridsome-web: Error: Type with name "SanityDocument" does not exists`

full log:
```
sanity-gridsome-web: > sanity-gridsome-web@ dev /Users/michahell/Documents/projects/tim/Yuri/web
sanity-gridsome-web: > gridsome develop
sanity-gridsome-web: Gridsome v0.7.1
sanity-gridsome-web: Initializing plugins...
sanity-gridsome-web: [sanity] `overlayDrafts` set to true, but no `token` specified!
sanity-gridsome-web: [sanity] Watch mode enabled, starting a listener
sanity-gridsome-web: Load sources - 1.12s
sanity-gridsome-web: Error: Type with name "SanityDocument" does not exists
sanity-gridsome-web:     at SchemaComposer.get (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/TypeStorage.js:44:13)
sanity-gridsome-web:     at ThunkComposer._ThunkComposer.ThunkComposer [as _thunk] (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/TypeMapper.js:562:34)
sanity-gridsome-web:     at ThunkComposer.get ofType [as ofType] (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/ThunkComposer.js:20:34)
sanity-gridsome-web:     at ThunkComposer.getUnwrappedTC (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/ThunkComposer.js:42:17)
sanity-gridsome-web:     at ThunkComposer.getType (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/ThunkComposer.js:46:17)
sanity-gridsome-web:     at ObjectTypeComposer.getFieldConfig (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/graphql-compose/lib/ObjectTypeComposer.js:286:18)
sanity-gridsome-web:     at processFields (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/gridsome/lib/graphql/createSchema.js:254:38)
sanity-gridsome-web:     at processTypes (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/gridsome/lib/graphql/createSchema.js:244:9)
sanity-gridsome-web:     at createSchema (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/gridsome/lib/graphql/createSchema.js:64:3)
sanity-gridsome-web:     at Schema.buildSchema (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/gridsome/lib/app/Schema.js:28:28)
sanity-gridsome-web:     at Plugins.createSchema (/Users/michahell/Documents/projects/tim/Yuri/web/node_modules/gridsome/lib/app/Plugins.js:93:22)
sanity-gridsome-web:     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by matsba** [comment]
Configuring schema for SanityDocument in gridsome.server.js fixed the issue for me:

```
  api.createSchema(({ addSchemaTypes }) => {
    addSchemaTypes(`
      type SanityDocument implements Node @infer {
        id: ID!
      }
    `)
  })
```
As seen on [here](https://github.com/sanity-io/sanity-template-gridsome-blog/blob/master/template/web/gridsome.server.js).

**Comment by hdoro** [comment]
This is fixed with #14 🎉

Upgrade your plugin to `^1.1.0` to get the solution above by default.
